### ISSUE TITLE
Application not working properly (anymore).

### ISSUE THREAD

**Issue by juriadams** [DrFair/TwitchBots#1]
Hello there!

I wanted to try out your application a few hours ago and was sad to realize, that after the hard installation, the program isn't working properly.

It may just be some trouble with installing the dependencies or some other stuff when switching between channels, there's something erroring every time.

I just wanted to let you know,

Juri A.

**Comment by DrFair** [comment]
Thanks for the reporting the issue, however I am having trouble reproducing it.
I just did some tests with a completely fresh install, and it seems to be working fine for me.
Can you paste the errors you are getting and maybe a bit more about when you are getting them?

Thanks!

**Comment by juriadams** [comment]
Hello again!

Well, that's indeed very, very weird...
I have now reinstalled everything and reinstalled all dependencies one by one. It appeared that there was an error with Python (?) which seems to be fixed now. 

Now, I'm having a little trouble with adding/logging in accounts.

As soon as I add accounts to the `users.json`, I'm getting an error which says the following:

`C:\Users\4dams\Desktop\GitHub\TwitchBots>node index.js
[Thu Oct 05 2017 15:00:14 GMT+0200 (Romance Daylight Time)] Started server at :::3000
Error on auth token oauth:(my token here)`

I'm pretty sure that this appears because I didn't authorize the bot with my application yet. When I want to click the button on the webpanel though, I'm getting this error:
```{"error":"Bad Request","status":400,"message":"No client id specified"}``` And it even states in the link, that get's opened:
```... base?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI ...```

I have my Redirect URI on twitch set to `/twitchauth`. The same as in the settings.json, where it is also set to `/twitchauth`


Unfortunately, I'm kinda stuck here and don't really know what to do, since I'd love to try out your neat little project here. :/

Thank you for helping me,

Juri A.

**Comment by DrFair** [comment]
Looks like your issue has to do with your settings.json.

Make sure that you first register a developer application on Twitch here:
https://dev.twitch.tv/dashboard/apps
Remember to set the redirect URI to the IP/hostname of the machine you run the server on.
Example: http://localhost:3000/twitchauth
Note that with localhost as redirect uri, you can only access the application from the host machine.

Once you have your application registered, set up your settings.json file exactly like the example on the readme, but with your own clientID and secret from Twitch.
Remember that your port and host name combination has to match the Twitch application redirect URI.

**Comment by juriadams** [comment]
Thank you very much!

It's working fine now and I was also able to set it up on my remote server.
Thank you for helping me with the setup!

And really awesome project, you made there!

Greetings from Germany,

Juri A.
